#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-nenv
Version  : 0.3.0
Release  : 3
URL      : https://rubygems.org/downloads/nenv-0.3.0.gem
Source0  : https://rubygems.org/downloads/nenv-0.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
[![Build Status](https://travis-ci.org/e2/nenv.png?branch=master)](https://travis-ci.org/e2/nenv)
[![Gem Version](http://img.shields.io/gem/v/nenv.svg)](http://badge.fury.io/rb/nenv)
[![Dependency Status](https://gemnasium.com/e2/nenv.svg)](https://gemnasium.com/e2/nenv)
[![Code Climate](https://codeclimate.com/github/e2/nenv/badges/gpa.svg)](https://codeclimate.com/github/e2/nenv)
[![Coverage Status](https://coveralls.io/repos/e2/nenv/badge.png)](https://coveralls.io/r/e2/nenv)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n nenv-0.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-nenv.gemspec

%build
gem build rubygem-nenv.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
nenv-0.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/nenv-0.3.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/AutoEnvironment/cdesc-AutoEnvironment.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/AutoEnvironment/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Builder/build-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Builder/cdesc-Builder.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/AlreadyExistsError/cdesc-AlreadyExistsError.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/AlreadyExistsError/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Dumper/Default/call-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Dumper/Default/cdesc-Default.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Dumper/cdesc-Dumper.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Dumper/setup-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Loader/Default/call-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Loader/Default/cdesc-Default.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Loader/Predicate/call-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Loader/Predicate/cdesc-Predicate.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Loader/cdesc-Loader.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/Loader/setup-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/MethodError/cdesc-MethodError.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/MethodError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/_create_env_accessor-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/_create_env_reader-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/_create_env_writer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/_fail_if_accessor_exists-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/_namespaced_sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/_sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/cdesc-Environment.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/create_method-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/create_method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/Environment/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/cdesc-Nenv.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/method_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/reset-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Nenv/respond_to%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Object/Nenv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/nenv-0.3.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/LICENSE.txt
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/autoenvironment.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/builder.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/environment.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/environment/dumper.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/environment/dumper/default.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/environment/loader.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/environment/loader/default.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/environment/loader/predicate.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/lib/nenv/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/nenv-0.3.0/nenv.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/nenv-0.3.0.gemspec
