#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-nenv
Version  : 0.3.0
Release  : 4
URL      : https://rubygems.org/downloads/nenv-0.3.0.gem
Source0  : https://rubygems.org/downloads/nenv-0.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
[![Build Status](https://travis-ci.org/e2/nenv.png?branch=master)](https://travis-ci.org/e2/nenv)
[![Gem Version](http://img.shields.io/gem/v/nenv.svg)](http://badge.fury.io/rb/nenv)
[![Dependency Status](https://gemnasium.com/e2/nenv.svg)](https://gemnasium.com/e2/nenv)
[![Code Climate](https://codeclimate.com/github/e2/nenv/badges/gpa.svg)](https://codeclimate.com/github/e2/nenv)
[![Coverage Status](https://coveralls.io/repos/e2/nenv/badge.png)](https://coveralls.io/r/e2/nenv)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n nenv-0.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-nenv.gemspec

%build
gem build rubygem-nenv.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
nenv-0.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/nenv-0.3.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/autoenvironment.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/environment/dumper.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/environment/dumper/default.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/environment/loader.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/environment/loader/default.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/environment/loader/predicate.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/lib/nenv/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/nenv-0.3.0/nenv.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/nenv-0.3.0.gemspec
